### ISSUE TITLE
Classes to remove a box shadow

### ISSUE THREAD

**Issue by rspt** [tachyons-css/tachyons-box-shadow#3]
Hello! 

I was wondering how we remove a box-shadow set with this module. Should we introduce classes like `.shadow-0` or `.no-shadow` in order to remove the shadow effect? Or is there another solution?

Thanks!

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
